apiVersion: v1
items:
- apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRouteTCP
  metadata:
    annotations:
    name: {{ include "helm.fullname" . }}
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: HostSNI(`{{ .Values.ingress.hostSNI }}`)
      services:
      - name: {{ include "helm.fullname" . }}
        port: {{ .Values.service.port }}
    tls:
      passthrough: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""